#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# changed to load another file
[ -f $HOME/.zshrc.d/.zshrc.user ] && source $HOME/.zshrc.d/.zshrc.user

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/Users/maginemu/.gvm/bin/gvm-init.sh" ]] && source "/Users/maginemu/.gvm/bin/gvm-init.sh"
